Implement a cosmwasm version of compass
palomachain/paloma-rs pull request #46
Opened 2022-09-09 13:18 UTC by measure-fi

https://github.com/palomachain/paloma/issues/447

## Background

Implement a cosmwasm version of compass. Most of this directly translates to a solana rust version, my intent is for these contracts to share types.

## Testing completed

- [ ] tbd

2022-09-09 13:24 UTC, measure-fi reviewed
@wc117 @webelf101 PTAL. Parts of this are broken out. I kind of want two levels of review

1. Does this PR implement compass correctly assuming the very specific bits are correct.
2. Are the very specific bits I have replicated (hash function, use of eth address vs paloma address in some places) correct or faulty.

Thanks!

2022-09-09 13:24 UTC, measure-fi commented on sol/compass-cw/src/contract.rs
> +    //     ecrecover(message_digest, sig.v, sig.r, sig.s),
So I cannot find a rust version of this function, like at all. I have found discussion and others have this problem, but it seems like I will have to implement it.

2022-09-09 13:24 UTC, measure-fi commented on sol/compass-cw/src/contract.rs
> +    let args_hash = keccak256(&ethabi::encode(&[
@wc117 Is there any way I can get "test vectors" for the hash functions used in this contract? I am fairly confident what is written here is wrong. By this I just mean a couple example input / output, so I can verify the encoding.

2022-09-09 13:24 UTC, measure-fi commented on sol/compass-cw/src/contract.rs
> +        // raw_call(args.logic_contract_address, args.payload);
The ultimate form here is dependent on how we do external calls, and will change for the Solana version.

2022-09-09 13:24 UTC, measure-fi commented on sol/compass-cw/src/msg.rs
> +            //turnstone_id(),
Need to re-add these.

2022-09-20 12:15 UTC, measure-fi commented on sol/compass-cw/src/contract.rs
> +            },
This might be cheating, since we're using compass here to call _external_ contracts? Should this be strictly internal ones?

2022-09-20 12:19 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +    TURNSTONE_ID.save(deps.storage, &msg.turnstone_id)?;
```suggestion
    SMART_CONTRACT_UNIQUE_ID.save(deps.storage, &msg.smart_contract_unique_id)?;
```
so that it matches what we have in Paloma

2022-09-20 12:21 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +    let mut hasher = Keccak256::new_with_prefix(b"\x19Paloma Signed Message:\n32");
No Keccak256. It is eth specific. Let us use https://lib.rs/crates/cosmwasm-crypto `secp256k1_verify`

2022-09-20 12:22 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +    let mut hasher = Keccak256::new_with_prefix(b"\x19Paloma Signed Message:\n32");
This is some ugly stuff from EVM and we don't want to drag this 💩 into rust

2022-09-20 12:25 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +            },
Nope. You could call any smart contract on any external chain that we support from a smart contract deployed to paloma.

2022-09-20 12:26 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +            },
Ohh I see. This is deployed to non-paloma chain, so having this CustomResponseMsg here doesn't make sense.

2022-09-20 12:29 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +        QueryMsg::TurnstoneId => to_binary(&TURNSTONE_ID.load(deps.storage)?),
```suggestion
        QueryMsg::SmartContractUniqueID => to_binary(&TURNSTONE_ID.load(deps.storage)?),
```

2022-09-20 12:32 UTC, Vizualni commented on sol/compass-cw/src/lib.rs
> +}
@measure-fi I'd rather if you and I agree on a way of serializing data and hashing it rather than using this thing which happens to be too generic and seems to me that it's kind of Rust specific. This is something that needs to work on both Go and Rust side. Given that we have only two entry points (update valset and submit logic call) we really don't need something too generic.

2022-09-20 15:36 UTC, measure-fi commented on sol/compass-cw/src/lib.rs
> +}
Discussed out of band, rather than synchronizing on a serialization method we will simply have the raw payload passed in. It can then be checked and deserialized.

2022-09-20 21:06 UTC, wc117 commented on sol/compass-cw/src/contract.rs
> +            },
I think we should call any other smart contract with wasm msg. But this looks like we are letting pigeons to run the other chain compass contract.

2022-09-21 13:16 UTC, measure-fi commented on sol/compass-cw/src/lib.rs
> +}
@Vizualni Still using bcs/keccak for the checkpointing. I don't know if you had other ideas about that or if it's just okay.

2022-09-21 13:24 UTC, Vizualni commented on sol/compass-cw/schema/execute_msg.json
> +        "pick_winner"
is this supposed to be here for the compass-cw?

2022-09-21 13:34 UTC, Vizualni commented on sol/compass-cw/schema/execute_msg.json
> +          ],
This file does not match the schema for the compass-ew's types

2022-09-21 13:34 UTC, Vizualni commented on sol/compass-cw/schema/instantiate_msg.json
> +    "TargetContractInfo": {
wrong schema?

2022-09-21 13:35 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +    SMART_CONTRACT_ID.save(deps.storage, &msg.smart_contract_id)?;
could you add ensure! to to check that smart_contract_id is set?

2022-09-21 13:39 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +    let hash = Keccak256::new().chain_update(msg).finalize();
why do you need to hash the msg and verify the signature against the hash instead of the message?

also, on a side note if you are up for hashing, could we use sha256 instead of keccak256? This is not something that natively exists in Go's crypto library and I'd hate to import a new one or even worse to depend on the EVM's own keccak256 which i am going to pull into the cosmwasm related package.

2022-09-21 13:43 UTC, Vizualni commented on sol/compass-cw/src/msg.rs
> +    pub logic_contract_address: Addr,
```suggestion
    pub contract_address: Addr,
```
?

2022-09-21 13:46 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +        QueryMsg::SmartContractId => to_binary(&SMART_CONTRACT_ID.load(deps.storage)?),
Could you also add a query message to get the last valset id that you're aware of?

2022-09-21 13:46 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +use crate::hex;
please write tests for all these functions here 🙏

2022-09-21 13:46 UTC, Vizualni commented on sol/compass-cw/src/msg.rs
> +    /// keccak256(abi_encode(checkpoint(validators, powers, valset_id, turnstone_id)))
no more abi_encode

2022-09-21 13:47 UTC, Vizualni commented on sol/compass-cw/src/msg.rs
> +        keccak256(&Checkpoint {
same comment as before about s/keccak256/sha256

2022-09-21 13:51 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +        deps.api.secp256k1_verify(&hash, &sig.0, signer.as_bytes()) == Ok(true),
Are you sure that secp256k1_verify works with the address and not the public key?

2022-09-21 14:03 UTC, Vizualni commented on sol/compass-cw/Cargo.toml
> +name = "compass-cw"
this is named compass-cosmwasm but it's in the sol folder. We chatted about this and it would be best if those two are separated and are not made from the same underlying code, but rather we need to make them compatible and make them work best in the environment where they are meant to run

2022-09-21 14:03 UTC, Vizualni commented on sol/compass-cw/src/contract.rs
> +};
cosmwasm for solana?

2022-09-21 17:13 UTC, measure-fi commented on sol/compass-cw/schema/execute_msg.json
> +        "pick_winner"
671454d2

2022-09-21 20:01 UTC, measure-fi commented on sol/compass-cw/src/contract.rs
> +    let hash = Keccak256::new().chain_update(msg).finalize();
`secp256k1_verify` specifies that the message hash is what is being signed, I don't know if that is a real requirement though. Perhaps either is fine, although the hash is much shorter and we're doing this many times.

2022-09-21 20:04 UTC, measure-fi commented on sol/compass-cw/src/contract.rs
> +    use crate::msg::ExecutePayload::*;
I never do top-level star imports (other than preludes or `super::*`). This is a minor pattern in rust (at least until `_::Variant` syntax gets unlocked) to import all of an enum's variants to use in a match.

2022-09-21 21:38 UTC, taariq commented
@measure-fi is this still pending?

2022-09-21 21:39 UTC, taariq commented on sol/compass-cw/Cargo.toml
> +name = "compass-cw"
@measure-fi what's the status here? Is this changed? I'm not sure what to share with external parties asking for this code access.

2022-09-22 09:24 UTC, Vizualni commented on sol/compass-cw/src/lib.rs
> +}
https://github.com/palomachain/paloma-rs/pull/46/files#r976532155

2022-09-22 12:58 UTC, measure-fi commented on sol/compass-cw/Cargo.toml
> +name = "compass-cw"
These were always going to be separate code bases. I can change the directory (I will probably rename it to `compass/`.

2022-09-22 13:14 UTC, measure-fi commented
@taariq I am mostly addressing outstanding comments.

2022-09-22 14:47 UTC, measure-fi commented on sol/compass-cw/src/contract.rs
> +    SMART_CONTRACT_ID.save(deps.storage, &msg.smart_contract_id)?;
This line errors currently if it has not been set.

2022-09-22 15:10 UTC, measure-fi commented on sol/compass-cw/src/contract.rs
> +        deps.api.secp256k1_verify(&hash, &sig.0, signer.as_bytes()) == Ok(true),
Out of band discussion, switching the key type to something more opaque (`Binary`). `Addr` is definitely wrong, although on other chains it corresponds directly to some kind of public key (and is probably what we want).

2022-09-23 10:06 UTC, Vizualni commented on compass/compass-cw/src/contract.rs
> +    ensure!(env.block.height < deadline, "Timeout");
```suggestion
    ensure!(env.block.height < deadline, "Timeout");
```

deadline is time in UTC. Could you check for env.block.time ?

2022-09-23 10:09 UTC, Vizualni commented on compass/compass-cw/src/msg.rs
> +    pub validators: Vec<Binary>,
what is this field validators? is it a vector of public keys or addresses?

2022-09-23 10:10 UTC, Vizualni commented on compass/compass-cw/src/msg.rs
> +pub struct Checkpoint<'a> {
Is this used somewhere?

2022-09-23 10:21 UTC, Vizualni commented on compass/compass-cw/src/contract.rs
> +        check_signature(deps, validator, hash.as_ref(), sig)?;
Not all validators from the current valset will provide their signature. At least I may not send all of them, so this needs to work with that in mind. I can simply send `null` in that case

2022-09-23 10:22 UTC, Vizualni commented on compass/compass-cw/src/msg.rs
> +    pub valset_id: ValsetId,
This is not really required anymore given that I am only sending signatures. On compass-evm it made sense to send because it was used against the make_checkpoint, while those checkpoints are not important here anymore.

2022-09-23 10:23 UTC, Vizualni commented on compass/compass-cw/src/msg.rs
> +    pub valset_id: ValsetId,
But valset_id in Valset struct is still required because pigeons need to know what is the current compass' valset id so they can know if there is a consensus or not

2022-09-23 10:24 UTC, Vizualni commented on compass/compass-cw/src/contract.rs
> +/// new valset. The signatures supplied are the signatures of the current valset over the checkpoint hash
this needs to be updated because checkpoints are not used here

2022-09-23 10:25 UTC, Vizualni commented on compass/compass-cw/src/contract.rs
> +    ensure!(new_valset.valset_id > valset_id, "Invalid Valset ID");
Could you add to the message why it's invalid?

2022-09-23 10:27 UTC, Vizualni commented on compass/compass-cw/src/contract.rs
> +        funds: info.funds,
This is something that we don't want to do. We don't want to move funds directly from our validator's external accounts. Could you add the check on top of the submit_logic_call if there are funds, then "throw an exception"?

2022-09-23 10:27 UTC, Vizualni commented on compass/compass-cw/src/contract.rs
> +        funds: info.funds,
We might want to have this for the wallet functionality, but we don't want to have this in submit_logic_call

2022-09-23 10:29 UTC, Vizualni requested changes
This is so much better now! Thank you for including the changes that we talked about it. Could you please write tests for this as well?

2022-09-23 10:30 UTC, Vizualni commented on compass/compass-cw/src/contract.rs
> +) -> Result<Response> {
Could you also add a check if `args.compass_addr == self.addr`, then raise an exception (whatever the rust lingo is)?

2022-09-23 13:10 UTC, measure-fi commented on compass/compass-cw/src/contract.rs
> +    ensure!(env.block.height < deadline, "Timeout");
Is it in seconds or millis? And would it be okay to indicate which in the name of the variable?

2022-09-23 13:10 UTC, measure-fi commented on compass/compass-cw/src/msg.rs
> +    pub validators: Vec<Binary>,
Public keys.

2022-09-23 13:14 UTC, measure-fi commented on compass/compass-cw/src/contract.rs
> +        check_signature(deps, validator, hash.as_ref(), sig)?;
Ah. We do need some way of mapping signatures to their stored validator. I will change the type of signatures to `pub signatures: Vec<Option<Signature>>,` and it will handle nulls.

2022-09-23 13:17 UTC, measure-fi commented on compass/compass-cw/src/msg.rs
> +    pub valset_id: ValsetId,
I think it's required only for this test:

```
// check if new valset_id is greater than current valset_id
ensure!(new_valset.valset_id > valset_id, "Invalid Valset ID");
```

otherwise there is the ability to downgrade the valset.

2022-09-23 13:29 UTC, measure-fi commented on compass/compass-cw/src/contract.rs
> +        funds: info.funds,
For now I will pass 0 funds?

2022-09-26 18:26 UTC, measure-fi commented on sol/compass-cw/src/contract.rs
> +    let hash = Keccak256::new().chain_update(msg).finalize();
It now uses sha256. Although as we add chains, I don't think you're going to get around needing a go version of keccak256.

2022-09-26 18:31 UTC, measure-fi commented on compass/compass-cw/src/contract.rs
> +) -> Result<Response> {
Ah, this is to prevent compass from recursively calling itself without a trampoline. Is this purely to avoid accidental self-calls? In any case I have added
```
    ensure!(
        args.contract_address != env.contract.address,
        "Probable error, recursive compass invocation"
    );
```

2022-09-27 10:20 UTC, Vizualni commented on compass/compass-cw/src/contract.rs
> +) -> Result<Response> {
Yep. This is also here just to kill a possible attack vector. Even though I don't see it, maybe somebody could have exploited this.

2022-09-27 10:21 UTC, Vizualni commented on compass/compass-cw/src/msg.rs
> +    pub valset_id: ValsetId,
Exactly. We only care about signatures that are being sent ;)

2022-09-28 17:07 UTC, measure-fi commented on compass/compass-cw/src/msg.rs
> +    pub valset_id: ValsetId,
Talked out of band. We were talking past each other. Valset id is a required property of the valset for updates. It is not a required property of `Consensus` because using the old valset but obtaining a consensus which aligns with the current valset is fine.

2022-10-06 14:02 UTC, Vizualni commented on compass/compass-cw/src/tests.rs
> +fn basic_workflow() -> Result<()> {
yay. nice to see those tests!

2022-10-06 14:04 UTC, merged