A register/claims contract for ethereum transactions.
palomachain/paloma-rs pull request #59
Opened 2023-02-05 12:46 UTC by measure-fi

## Related Issues

- _list relevant github issues here_

## Background

_A short paragraph on test what exactly this PR solves._

## Testing completed

- [ ] _a list of actions that you've performed to ensure that this PR works as intended_
- [ ] _99% of the times you should have an item: "wrote tests"_

2023-02-05 12:50 UTC, measure-fi commented on claims/register/src/contract.rs
> +            ensure!(&tx_hash.as_bytes() == &hash, "invalid signature");
@verabehr So this is where we check the _hash_. There is no (actual) signature in the requested API https://github.com/palomachain/paloma-nest-service/pull/2; I'd like to know how this is actually meant to be validated (without a challenge/response pair).

2023-02-05 12:50 UTC, measure-fi commented on claims/register/src/contract.rs
> +                amount: vec![coin(tx_meta.amount.u128(), "XXX: what goes here?")],
The note `"XXX: what goes here?"` is wrt to denom, I think the API needs to be adjusted to send a denom as well.

2023-02-05 12:50 UTC, measure-fi commented on claims/register/src/contract.rs
> +        ExecuteMsg::Withdraw { funds } => {
Not sure if this should be withdraw or withdraw_all.

2023-02-05 12:50 UTC, measure-fi commented on claims/register/src/contract.rs
> +                res = res.add_attribute(&coin.denom, amt);
Poor man's query. But we can add queries to this contract.

2023-02-06 14:34 UTC, verabehr commented on claims/register/src/contract.rs
> +        ExecuteMsg::Withdraw { funds } => {
withdraw_all

2023-02-06 14:38 UTC, verabehr commented on claims/register/src/contract.rs
> +                amount: vec![coin(tx_meta.amount.u128(), "XXX: what goes here?")],
@wdev733 ?

2023-02-06 14:38 UTC, verabehr commented on claims/register/src/contract.rs
> +            ensure!(&tx_hash.as_bytes() == &hash, "invalid signature");
@wdev733

2023-02-06 14:55 UTC, verabehr commented on claims/register/src/contract.rs
> +            ensure!(&tx_hash.as_bytes() == &hash, "invalid signature");
Separately, I think this logic needs to go into the register function. The registration happens on successful swap by the user.

2023-02-06 14:58 UTC, verabehr commented on claims/register/src/contract.rs
> +        ExecuteMsg::Withdraw { funds } => {
withdraw is fine

2023-02-06 16:30 UTC, wdev733 commented on claims/register/src/contract.rs
> +                amount: vec![coin(tx_meta.amount.u128(), "XXX: what goes here?")],
@verabehr I think we need to add 1 more parameter to api - `txHash`
The contract should save at least 4 values - chainId, txHash, userPalomaWalletAddress, and amount.
The `chainId` and `txHash` will be used to prevent double claim registeration.
cc: @rootedbox

2023-02-06 16:41 UTC, wdev733 commented on claims/register/src/contract.rs
> +            ensure!(&tx_hash.as_bytes() == &hash, "invalid signature");
@measure-fi @verabehr 
`register` function
- should check the input parameters (address, amount, chainId, txHash) by signature and signer address.
- Add the amount to a variable for claiming (for example: claimable[address])

`claim` function
- reduce the above `claimable[address` by claimed amount
- send grains to user

what do you think ?

2023-02-06 16:45 UTC, verabehr commented on claims/register/src/contract.rs
> +                amount: vec![coin(tx_meta.amount.u128(), "XXX: what goes here?")],
https://github.com/palomachain/paloma/issues/706

2023-02-06 16:47 UTC, verabehr commented on claims/register/src/contract.rs
> +            ensure!(&tx_hash.as_bytes() == &hash, "invalid signature");
agreed

2023-02-06 16:47 UTC, verabehr requested changes
see inline comments

2023-02-11 00:25 UTC, verabehr commented on claims/register/src/contract.rs
> +                info.sender == ADMIN.load(deps.storage)?,
@measure-fi  I don't think we want this line. Since the user's wallet is registering the claim, I don't think this would work if only admins can register. @wdev733 please confirm cc @taariq

2023-02-13 15:38 UTC, wdev733 commented on claims/register/src/contract.rs
> +                info.sender == ADMIN.load(deps.storage)?,
I agree @verabehr @measure-fi 
I am not aware this code well. but all users should have permissions for registering and claiming rewards.

2023-02-14 08:01 UTC, measure-fi commented on claims/signed_claims/src/contract.rs
> +            //);
@wdev733 I still need to fill out this block, but does the rest of the logic here look sound or is this way off the mark?

2023-02-14 20:35 UTC, measure-fi commented on claims/signed_claims/src/contract.rs
> +            REWARDS.save(deps.storage, tx.address.clone(), &amount)?;
Note to self, as written double submit works (it shouldn't)

2023-03-02 16:41 UTC, verabehr approved these changes

2023-03-02 16:45 UTC, merged